# Generated by Django 4.2.1 on 2023-05-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="picturelist",
            name="sub_category",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
