# Generated by Django 4.2.1 on 2023-05-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_picturelist_sub_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerdata",
            name="match_score",
            field=models.PositiveBigIntegerField(default=50),
        ),
    ]
