# Generated by Django 4.2.1 on 2023-05-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_workerdata_accept_alter_workerdata_completed_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picturelist",
            name="stock_line",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.stocklist",
            ),
        ),
    ]
